version: 2
jobs:
  build:
    working_directory: ~/CircleCIDemo
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Decrypt encrypted keystore file
          command: source script/setup_environment.sh && decrypt_keystore
      - run:
          name: Set up signing configuration
          command: source script/setup_environment.sh && setup_signing_config
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Build debug apk
          command: ./gradlew assembleDebug
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk
      - store_test_results:
          path: app/build/test-results
      - deploy:
          name: Deploy to deploygate
          command: source script/setup_deploygate.sh